source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target "Energyhack" do
 pod 'AeroGear-Push-Swift'
 pod 'Alamofire'
 pod 'AlamofireObjectMapper', '~> 4.0'
end
